import React, { useState, useEffect } from 'react'
import axios from 'axios'


const Home = () => {
  const [loading, setLoading] = useState(false)
  const [allPost, setAllPost] = useState(null)

  useEffect(() => {
    setLoading(true)
    const getAllPost = async () => {
      try {
        const res = await axios.get(`${import.meta.env.VITE_SERVER_URL}/api/v1/post`)
        console.log(`${import.meta.env.VITE_SERVER_URL}/api/v1/post`)
        setAllPost(res.data.data)
      } catch (error) {
        console.log(error)
      } finally {
        setLoading(false)
      }
    }
    getAllPost()
  }, [])
  return (
    <section className='max-w-7xl mx-auto my-8 px-4 md:px-8'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-4xl'>The Community ShowCase</h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w-3xl'>Browse through a collection of imaginative and visually stunning images generated by DALL.E AI</p>
        <div>
          <div class="py-6 sm:py-8 lg:py-12">
            <div class="mx-auto max-w-screen-2xl">
              <div class="grid grid-cols-2 gap-4 sm:grid-cols-3 md:gap-6 xl:gap-8">
                {allPost && allPost.map((post , i) => {

                  return <span class={`${"group relative flex h-48 items-end overflow-hidden rounded-lg bg-gray-100 shadow-lg md:h-80"} ${(i + 1) % 7 == 1 && 'md:col-span-2'} ${(i + 1) % 7 == 0 && 'md:col-span-2'}`}>
                    <img src={post.photo} loading="lazy" alt={post.prompt} class="absolute inset-0 h-full w-full object-cover object-center transition duration-200 group-hover:scale-110" />
                    <div className='absolute inset-0 bg-black bg-opacity-40 p-4 group-hover:translate-y-0 translate-y-96 duration-300 ease-in-out'>
                      <div className='text-right mb-auto'>
                        <a target='_blank' href={post.photo} className='bg-indigo-500 hover:bg-indigo-600 text-white px-4 py-2 rounded-md'>OPEN</a>
                      </div>
                      <div className='absolute bottom-4 pl-2 pr-4 w-full flex justify-between items-center'>
                        <div className='w-[75%]'>
                            <p className='text-white text-sm font-medium'>{post.prompt}</p>
                        </div>
                        <div className='w-[20%]'>
                            <p className='text-white text-sm font-medium'>By {post.name}</p>
                      </div>
                        </div>
                    </div>
                  </span>

                })}
              </div>
            </div>
          </div>
        </div>
        <div className="mt-10">
          {loading && (
            <div className="flex justify-center items-center">
              <div role="status">
                <svg aria-hidden="true" className="inline w-10 h-10 mr-2 text-gray-200 animate-spin fill-[#6469ff]" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor" />
                  <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill" />
                </svg>
              </div>
            </div>
          )}
        </div>
      </div>

    </section>
  )
}

export default Home